### ISSUE TITLE
[enhancement] add a way to specify the preferences file name

### ISSUE THREAD

**Issue by 0xjohnnycagewins** [soarcn/Favor#11]
When using [getSharedPreferences(java.lang.String, int)](https://developer.android.com/reference/android/content/Context.html#getSharedPreferences%28java.lang.String, int%29) instead of [getDefaultSharedPreferences(android.content.Context)](https://developer.android.com/reference/android/preference/PreferenceManager.html#getDefaultSharedPreferences%28android.content.Context%29), you have to specify the preferences file name. It would be nice to have a way to specify that file name to Favor so that `getSharedPreferences(java.lang.String, int)` would be called using it. The idea is to keep the old preferences when migrating to Favor in an application that was already using `getSharedPreferences(java.lang.String, int)` without losing the current preferences or having to do a migration.

**Comment by soarcn** [comment]
@cartierjf  When you construct the FavorAdapter builder, you can specify your own share preference instance 
https://github.com/soarcn/Favor/blob/master/library/src/main/java/com/cocosw/favor/FavorAdapter.java#L93

**Comment by 0xjohnnycagewins** [comment]
Didn't catch that. Thanks!

**Comment by soarcn** [comment]
``` java
sp = getContext().getSharePreferences("youfilename",PRIVITE);
account = new FavorAdapter.Builder(sp).build().create(Account.class);
account.setPassword("Passw0rd");
String username = account.getUserName();
```
