### ISSUE TITLE
Clear Preference

### ISSUE THREAD

**Issue by razor-rs** [soarcn/Favor#3]
Can I clear prefernce file with this library ?

**Comment by soarcn** [comment]
@razor-rs  no, I suggest that you do this out of Favor. it's a small user case and I don't want to introduce more api for it.

``` java
SharedPreferences sp = getContext().getSharedPreferences("user", Context.MODE_PRIVATE);
FavorAdapter userAdapter = new FavorAdapter.Builder(sp).build();
sp.editor().clear().commit();
```

**Comment by 0xjohnnycagewins** [comment]
I also don't feel that it's an edge case and would be a nice enhancement
