### ISSUE TITLE
提一个小BUG

### ISSUE THREAD

**Issue by MakerYan** [soarcn/Favor#6]
当字段使用Favor声明key时,例如 @Favor("zi_duan") , 以此只将值存进去,而取不出来;

后来发现问题所在, 是因为需要在set来get上面都要声明;

**Comment by soarcn** [comment]
字段是不支持的， 如果你查看Favor声明，你会发现 @Target(METHOD)
在IDE上，你应该会收到报错消息才是

**Comment by MakerYan** [comment]
嗯,是的,如果要自定义key就需要在get和set方法上同样要声明@favor, 看了源码, 希望以后可以支持非接口类, 非常感谢!

**Comment by soarcn** [comment]
@MakerYan 什么情况需要非接口类呢？

**Comment by MakerYan** [comment]
就比如说, 网络请求回来的数据转换成对象, 而对象是Class, 而这个对象中有某些字段是需要存储在本地的, 按照现在的逻辑, 需要将该字段取出, 然后再存入封装的接口了;

**Comment by soarcn** [comment]
1 基本上不应该把缓存放到sharepreference
2 如果你需要下载一个配置文件写到sp里面，应该考虑写一个代码解析并写入sp（使用android的原生api）， 只把favor作为读取接口。
3 如果你有一个object一定需要放到sp， Favor可以直接保存一个Serializable 对象， 可以查看readme里面的说明

**Comment by MakerYan** [comment]
说明我之前全都看了, 谢谢! 我力挺你
